import type { MissionDef } from "@/lib/content";

/** Mission framework (spec §25). Objectives verified via server-recorded events. */
export const MISSIONS: MissionDef[] = [
  {
    id: "mission-01",
    order: 1,
    title: "Meet the Machine",
    description: "Learn what AI actually is and sort real systems from lookalikes.",
    minutes: 8,
    difficulty: "Easy",
    xp: 100,
    href: "/academy/ai-fundamentals/what-is-ai",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Complete the lesson 'What Is AI?'", event: { type: "lesson", id: "fund-what-is-ai" } },
      { id: "o2", label: "Sort the systems in 'AI or Not?'", event: { type: "interactive", id: "ai-or-not" } },
      { id: "o3", label: "Pass the knowledge check (quiz)", event: { type: "quiz", id: "quiz-fund-1" } },
    ],
  },
  {
    id: "mission-02",
    order: 2,
    title: "Train Your First Model",
    description: "Use the ML simulator to train a pass/fail classifier on student data.",
    minutes: 10,
    difficulty: "Easy",
    xp: 150,
    href: "/lab/train-the-machine",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Open the Train the Machine lab", event: { type: "sim", id: "train-machine:open" } },
      { id: "o2", label: "Train a model on the default dataset", event: { type: "sim", id: "train-machine:trained" } },
      { id: "o3", label: "Reach 80%+ accuracy on the test split", event: { type: "sim", id: "train-machine:accuracy-80" } },
    ],
  },
  {
    id: "mission-03",
    order: 3,
    title: "Break the Model",
    description: "Push the simulator into a corner: make the data fool the model.",
    minutes: 10,
    difficulty: "Medium",
    xp: 150,
    href: "/lab/train-the-machine",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Train with a one-sided (imbalanced) dataset", event: { type: "sim", id: "train-machine:imbalanced" } },
      { id: "o2", label: "Get test accuracy under 60% and read why", event: { type: "sim", id: "train-machine:broken" } },
    ],
  },
  {
    id: "mission-04",
    order: 4,
    title: "Prompt Upgrade",
    description: "Take a weak prompt to 80+ in the Prompt Lab.",
    minutes: 10,
    difficulty: "Medium",
    xp: 150,
    href: "/lab/prompt-lab",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Analyze any prompt in the lab", event: { type: "prompt", id: "prompt:analyzed" } },
      { id: "o2", label: "Rewrite to reach a score of 80+", event: { type: "prompt", id: "prompt:score-80" } },
    ],
  },
  {
    id: "mission-05",
    order: 5,
    title: "Catch the Hallucination",
    description: "Investigate AI responses and expose invented facts.",
    minutes: 12,
    difficulty: "Medium",
    xp: 150,
    href: "/detective",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Open a detective case file", event: { type: "detective", id: "detective:opened" } },
      { id: "o2", label: "Solve 3 cases correctly", event: { type: "detective", id: "detective:3-correct" } },
      { id: "o3", label: "Catch at least one hallucination", event: { type: "detective", id: "detective:hallucination" } },
    ],
  },
  {
    id: "mission-06",
    order: 6,
    title: "The Bias Case",
    description: "Find why a scholarship recommender treats students unfairly.",
    minutes: 12,
    difficulty: "Medium",
    xp: 175,
    href: "/lab/bias-simulation",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Inspect the recommendation outcomes", event: { type: "sim", id: "bias:ran" } },
      { id: "o2", label: "Identify the suspect feature driving the gap", event: { type: "sim", id: "bias:identified" } },
      { id: "o3", label: "Remove it and re-check the results", event: { type: "sim", id: "bias:fixed" } },
    ],
  },
  {
    id: "mission-07",
    order: 7,
    title: "Privacy Under Pressure",
    description: "Decide what data an AI tutoring app actually needs.",
    minutes: 8,
    difficulty: "Easy",
    xp: 150,
    href: "/ethics/privacy",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Complete 3 privacy scenarios", event: { type: "privacy", id: "privacy:3-done" } },
      { id: "o2", label: "Spot every unnecessary data request in one scenario", event: { type: "privacy", id: "privacy:perfect" } },
    ],
  },
  {
    id: "mission-08",
    order: 8,
    title: "The Ethical Review",
    description: "Sit in the Ethics Court and review a school AI deployment.",
    minutes: 15,
    difficulty: "Hard",
    xp: 175,
    href: "/ethics/court",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Review one Ethics Court case", event: { type: "ethics", id: "ethics:reviewed" } },
      { id: "o2", label: "Cover 75%+ of the important questions", event: { type: "ethics", id: "ethics:coverage-75" } },
    ],
  },
  {
    id: "mission-09",
    order: 9,
    title: "Build an AI Policy",
    description: "Draft a responsible-use policy for AI in your classroom.",
    minutes: 12,
    difficulty: "Medium",
    xp: 175,
    href: "/ethics/policy-builder",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Choose rules for at least 4 scenarios", event: { type: "ethics", id: "policy:4-rules" } },
      { id: "o2", label: "Publish your policy", event: { type: "ethics", id: "policy:published" } },
    ],
  },
  {
    id: "mission-10",
    order: 10,
    title: "FINAL BOSS: The Deployment Decision",
    description: "The capstone. Evaluate a full school AI proposal end to end.",
    minutes: 25,
    difficulty: "Hard",
    xp: 500,
    href: "/final-challenge",
    requiresEvents: true,
    objectives: [
      { id: "o1", label: "Complete every stage of the Final Challenge", event: { type: "final", id: "final:completed" } },
    ],
  },
];

export function missionById(id: string) {
  return MISSIONS.find((m) => m.id === id);
}
